# NumPy - Zadania

* Dokumentacja NumPy: http://docs.scipy.org/doc/numpy/reference/
* Tutorial NumPy: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

## Zadania 1.1

1. Za pomocą jednowierszowego polecenia utwórz następującą macierz:
$a =
\begin{pmatrix}
1       & 2      & \cdots & 10      \\
11      & 12     & \cdots & 20      \\
\vdots  & \ddots & \ddots & \vdots  \\
41      & 42     & \cdots & 50 
\end{pmatrix}$
2. Za pomocą metod obiektu `array`: 
 * określ liczbę elementów, kolumn i wierszy,
 * stwórz wektory średnich po wierszach oraz po kolumnach,
 * wypisz trzecią kolumnę macierzy `a`.
3. Przetestuj i opisz w jednym zdaniu działanie następujących funkcji: 
 * `np.log(a)` 
 * `np.cumsum(a)`
 * `np.rank(a)`
 * `np.power(a,2)`
4. Stwórz wektor składający się z 50 losowych punktów z przedziału 14 do 31

In [5]:
import numpy as np

print("zad.1")
a = np.arange(1, 51, 1).reshape(5,10)
print(a)

print("zad.2")
print("liczba wierszy i kolumn:")
print(a.shape) 
print("liczba elementów:")
print(a.size) 

print("średnia po wierszach:")
print(a.mean(axis = 1))

print("średnia po kolumnach:")
print(a.mean(axis = 0))

print("trzecia kolumna:")
print(a[:, 2])

print("zad.3")
print("log(a)- każdy element wektora zastępuje logarytmem naturalnym z tego elementu")
#np.log(a)
print("np.cumsum(a) - w przypadku wektora zwraca wektor kumulowanych sum np. dla [1,2,3] zwróci [1, 1+2, 1+2+3], czyli [1, 3, 6].")
print("W przypadku macierzy zwraca macierz z kumulowanymi sumami dla każdej kolumny")    
#np.cumsum(a)
print("np.rank(a) - wyznacza rząd macierzy")
#np.rank(a)
print("np.power(a,2) - podnosi do potęgi 2 każdy element macierzy")
#np.power(a,2)
print("zad.4")
print(np.random.randint(14,32,50))


zad.1
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
zad.2
liczba wierszy i kolumn:
(5, 10)
liczba elementów:
50
średnia po wierszach:
[  5.5  15.5  25.5  35.5  45.5]
średnia po kolumnach:
[ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
trzecia kolumna:
[ 3 13 23 33 43]
zad.3
log(a)- każdy element wektora zastępuje logarytmem naturalnym z tego elementu
np.cumsum(a) - w przypadku wektora zwraca wektor kumulowanych sum np. dla [1,2,3] zwróci [1, 1+2, 1+2+3], czyli [1, 3, 6].
W przypadku macierzy zwraca macierz z kumulowanymi sumami dla każdej kolumny
np.rank(a) - wyznacza rząd macierzy
np.power(a,2) - podnosi do potęgi 2 każdy element macierzy
zad.4
[19 29 17 26 23 25 23 22 18 17 16 16 15 23 30 21 31 17 30 26 24 14 27 26 19
 21 22 14 24 20 22 23 31 14 28 21 27 23 15 19 20 16 18 22 19 22 19 31 28 14]


# Zadania 1.2

Zapisz i oblicz za pomocą NumPy
1. Iloczyn macierzy $A$ z wektorem $\vec{x}$:
$$\begin{align*}
  A \vec{x} &= \left[
    \begin{array}{rrr}
      1 & -1 & 2\\
      0  & -3 & 1
    \end{array}
  \right]
  \left[
    \begin{array}{l}
      2\\1\\0
    \end{array}
  \right]
  =
  \left[
    \begin{array}{r}
      1\\
      -3
    \end{array}
  \right].
\end{align*}$$

2. Iloczyn macierzy $A$ i $B$:  
$$\begin{align*}
  AB &=\left[
      \begin{array}{rrr}
        0 & 4 & -2\\
        -4 & -3 & 0
      \end{array}
    \right] 
    \left[
      \begin{array}{rr}
        0 &1\\
        1 & -1\\
        2 & 3
      \end{array}
    \right]
    =
    \left[
      \begin{array}{rr}
        0 & -10\\
        -3 & -1
      \end{array}
    \right].
  \end{align*}$$
  
3. Pokaż, że dla powyższych macierzy $A$ i $B$ prawdą jest, że $(AB)^T = B^TA^T$.  
4. Oblicz $\det(AB)$ (wyznacznik iloczynu $AB$).
4. Czym różni się operacja `A**-1` dla obiektów typu `array` i `matrix`? Pokaż na przykładzie. 
6. Dla macierzy $X = \left[
      \begin{array}{rrr}
        1 & 2 & 3\\
        1 & 3 & 6 \\
      \end{array}
    \right]$ oraz wektora $\vec{y} = \left[
      \begin{array}{r}
        5 \\
        6 \\
      \end{array}
    \right]$ oblicz wynikowy wektor: 
$$\vec{\theta} = (X^TX)^{-1}X^T\vec{y}.$$ Wykonaj te same obliczenia raz na obiektach typu `array` i raz na obiektach typu `matrix`. W przypadku obiektów typu `matrix` zastosuj możliwie krótki zapis. 

In [9]:
import numpy as np

print("zad.1")
A = np.array([[1, -1, 2], [0, -3, 1]])
x = [2,1,0]

print(np.dot(A, x))

print("zad.2")
A = np.array([[0,4,-2], [-4,-3,0]])
B = np.array([[0, 1], [1, -1], [2, 3]])
print(np.dot(A, B))

print("zad.3")
C = np.dot(A, B)
print("transpozycja iloczynu:")
print(C.transpose())

print("iloczyn transpozycji:")
print(np.dot(B.transpose(), A.transpose()))
print("odpowiedź: są równe")

print("zad.4")
print(np.linalg.det(C))

print("zad.5")
print(" dla obiektu array A**-1 podnosi każdy element do potęgi (-1) a następnie rzutuje wynik na typ danych, który jest w A (int na int, float na float itp)")
print("dla obiektu matrix A**-1 oblicza macierz odwrotną do macierzy A")

print("przykład array:")
ex1 = np.array([[1,2], [3,4]])
print(ex1**-1)
print("przykład matrix:")
ex2 = np.matrix('1 2; 3 4')
print(ex2**-1)

print("zad.6")
print("array:")
X = np.array([[1,2,3], [1,3,6]])
y = np.array([5,6])
theta = np.dot(np.dot(np.linalg.inv(np.dot(X.transpose(), X)), X.transpose()), y)
print(theta)
print("matrix:")
Xm = np.matrix('1,2,3; 1,3,6')
ym = np.matrix('5; 6')
thetam = ((Xm.T*Xm)**-1)*Xm.T*ym
print(thetam)


zad.1
[ 1 -3]
zad.2
[[  0 -10]
 [ -3  -1]]
zad.3
transpozycja iloczynu:
[[  0  -3]
 [-10  -1]]
iloczyn transpozycji:
[[  0  -3]
 [-10  -1]]
odpowiedź: są równe
zad.4
-30.0
zad.5
 dla obiektu array A**-1 podnosi każdy element do potęgi (-1) a następnie rzutuje wynik na typ danych, który jest w A (int na int, float na float itp)
dla obiektu matrix A**-1 oblicza macierz odwrotną do macierzy A
przykład array:
[[1 0]
 [0 0]]
przykład matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
zad.6
array:
[-7.      2.5     0.0625]
matrix:
[[-7.    ]
 [ 2.5   ]
 [ 0.0625]]
